security:
  # How is the user password hashed.
  password_hashers:
    src\Entity\User:
      algorithm: auto

  # Class in charge of validating and creating the user identity.
  providers:
    app_user_provider:
      entity:
        class: src\Entity\User
        property: username

  # Main firewall for the application. Interceptor for all requests before they arrive to the controller layer.
  firewalls:
    main:
      pattern: ^/
      stateless: false
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: home
      logout:
        path: app_logout
        target: /login
      access_token:
        token_handler: src\Security\AccessTokenHandler
        token_extractors:
          - 'header'

  # Manage access permissions for users based on their roles.
  access_control:
    - { path: ^/(login|register), roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
