security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        generate_jwt:
            pattern: ^/api/v1/generate-jwt$
            stateless: true
            json_login:
                check_path: /api/v1/generate-jwt
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            pattern: ^/
            stateless: false
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: home
            logout:
                path: app_logout
                target: /login

    access_control:
        - { path: ^/api/v1/generate-jwt, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/(login|register), roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
