framework:
    validation:
        enable_attributes: true
        auto_mapping: []
        mapping:
            paths: []

when@test:
    framework:
        validation:
            not_compromised_password: false
