# config/packages/validator.yaml
framework:
    validation:
        enable_attributes: true
        auto_mapping: []
        # Desactiva explícitamente la carga de mapping
        mapping:
            paths: []

when@test:
    framework:
        validation:
            not_compromised_password: false
