controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_generate_jwt:
    path: /generate-jwt
    controller: App\Controller\JWTController::generateJWT
    methods: POST
